---
- name: install_MySQL-python
  yum:
    name: MySQL-python
    state: latest
  tags:
    - pre_install
    - intall_MySQL-python

- name: add_mysql_user
  user:
    name: mysql
    create_home: no
    shell: /sbin/nologin
  tags:
    - pre_install
    - add_mysql_user

